const CLASS12_CONTENT=[
{title:'Electric Charges and Fields',topics:['Electric charge','Coulomb’s law','Superposition principle','Electric field','Electric field lines','Electric dipole','Electric flux','Gauss’s law','Applications of Gauss’s law']},
{title:'Electrostatic Potential and Capacitance',topics:['Electric potential','Potential difference','Potential due to a point charge','Equipotential surfaces','Potential energy','Conductors in electrostatics','Dielectrics','Capacitance','Combination of capacitors','Energy stored in a capacitor']},
{title:'Current Electricity',topics:['Electric current','Drift velocity','Ohm’s law','Resistance','Resistivity','Temperature dependence of resistance','Series and parallel resistors','Cells and internal resistance','Kirchhoff’s laws','Wheatstone bridge','Meter bridge','Potentiometer']},
{title:'Moving Charges and Magnetism',topics:['Magnetic force','Lorentz force','Motion of charged particle in magnetic field','Biot–Savart law','Ampere’s law','Magnetic field due to current','Force between parallel currents','Current loop as magnetic dipole','Solenoid','Moving coil galvanometer']},
{title:'Magnetism and Matter',topics:['Magnetic dipole','Bar magnet','Earth’s magnetism','Magnetic field and magnetic elements','Magnetic materials','Magnetisation','Magnetic susceptibility','Hysteresis','Permanent magnets','Electromagnets']},
{title:'Electromagnetic Induction',topics:['Magnetic flux','Faraday’s laws','Lenz’s law','Motional emf','Self-inductance','Mutual inductance','Eddy currents','AC generator']},
{title:'Alternating Current',topics:['AC voltage and current','RMS values','Phasors','AC through resistor','AC through inductor','AC through capacitor','LCR circuit','Resonance','Power in AC circuit','Transformer']},
{title:'Electromagnetic Waves',topics:['Displacement current','Electromagnetic waves','Properties of electromagnetic waves','Electromagnetic spectrum','Radio waves','Microwaves','Infrared radiation','Visible radiation','Ultraviolet radiation','X-rays','Gamma rays']},
{title:'Ray Optics and Optical Instruments',topics:['Reflection of light','Refraction of light','Spherical mirrors','Mirror formula','Refraction at spherical surfaces','Lenses','Lens maker’s formula','Lens formula','Prism','Total internal reflection','Optical fibres','Microscope','Telescope']},
{title:'Wave Optics',topics:['Huygens principle','Wavefronts','Interference','Young’s double-slit experiment','Coherent sources','Diffraction','Polarisation']},
{title:'Dual Nature of Radiation and Matter',topics:['Photoelectric effect','Einstein’s photoelectric equation','Photon concept','Matter waves','de Broglie wavelength','Davisson–Germer experiment']},
{title:'Atoms',topics:['Rutherford atomic model','Bohr atomic model','Hydrogen spectrum','Energy levels','Atomic transitions','Limitations of Bohr model']},
{title:'Nuclei',topics:['Nuclear composition','Nuclear size','Mass defect','Binding energy','Nuclear force','Radioactivity','Radioactive decay law','Half-life','Nuclear fission','Nuclear fusion']},
{title:'Semiconductor Electronics',topics:['Energy bands','Intrinsic semiconductor','Extrinsic semiconductor','p-n junction','Semiconductor diode','Rectifier','Zener diode','LED','Photodiode','Solar cell','Transistor','Logic gates']},
{title:'Communication Systems',topics:['Elements of communication','Bandwidth','Signal propagation','Ground wave','Sky wave','Space wave','Modulation','Amplitude modulation','Antennas']}
];
let chapter=0,topic=0;const key='kp12_mastered';
function done(){return JSON.parse(localStorage.getItem(key)||'{}')}
function total(){return CLASS12_CONTENT.reduce((n,c)=>n+c.topics.length,0)}
function styles(){const s=document.createElement('style');s.textContent='.master-wrap{margin-top:20px}.chapters{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.chapters button,.actions button,.practice{border:1px solid #dfe7f1;background:#fff;color:#0b1930;padding:10px 13px;border-radius:9px;font-weight:700;cursor:pointer;text-decoration:none}.chapters button.active,.actions .next{background:#1687ff;color:#fff;border-color:#1687ff}.progress{background:#fff;padding:15px 18px;border:1px solid #dfe7f1;border-radius:14px;margin-bottom:18px}.bar{height:8px;background:#e8eef6;border-radius:99px;margin-top:9px;overflow:hidden}.bar i{display:block;height:100%;background:#1687ff}.card{background:#fff;border:1px solid #dfe7f1;border-radius:16px;padding:26px;box-shadow:0 6px 22px #0b19300d}.tag{color:#1687ff;font-weight:800;font-size:13px}.card h2{font-size:30px;margin:12px 0 20px}.learn{font-size:17px;line-height:1.8;color:#47566b;background:#f7faff;padding:20px;border-radius:12px}.example{margin-top:14px;padding:15px;border-left:4px solid #1687ff;background:#f1f6ff}.master{display:flex;justify-content:space-between;gap:15px;align-items:center;margin-top:20px;padding:16px;background:#f7faff;border-radius:12px}.master button{border:0;background:#0b1930;color:#fff;padding:11px 15px;border-radius:8px;font-weight:700;cursor:pointer}.master.done{background:#eefaf2}.master.done button{background:#208b4c}.actions{display:flex;justify-content:space-between;gap:10px;margin-top:20px}.practice{background:#edf5ff;color:#1687ff}.visual{margin-top:20px;padding:25px;text-align:center;background:#f7faff;border-radius:12px;font-size:42px}.visual small{display:block;font-size:13px;color:#68758a;margin-top:8px}@media(max-width:650px){.card h2{font-size:24px}.master,.actions{flex-direction:column;align-items:stretch}.chapters{display:grid;grid-template-columns:1fr 1fr}}';document.head.appendChild(s)}
function render(){const root=document.getElementById('mastery');if(!root)return;styles();const c=CLASS12_CONTENT[chapter],t=c.topics[topic],d=done()[chapter+'-'+topic],n=Object.keys(done()).length;root.innerHTML=`<div class="top"><a href="index.html">← Back to Home</a><a href="question-bank.html">Question Bank →</a></div><h1>Class 12 <span>Physics</span></h1><p class="intro">Master one concept at a time. You may continue in this chapter or choose another chapter whenever you want.</p><div class="progress"><b>Mastery Progress</b><span style="float:right;color:#1687ff">${n}/${total()} concepts</span><div class="bar"><i style="width:${n/total()*100}%"></i></div></div><div class="chapters">${CLASS12_CONTENT.map((x,i)=>`<button class="${i===chapter?'active':''}" onclick="openChapter(${i})">${i+1}. ${x.title}</button>`).join('')}</div><div class="card"><span class="tag">Chapter ${chapter+1} • ${c.title}</span><h2>Concept ${topic+1}: ${t}</h2><div class="learn"><b>Learn this concept</b><p>${explain(t)}</p><div class="example"><b>Example / focus:</b> ${example(t)}</div></div><div class="visual">⚡<small>Physics concept visual — detailed diagram will be added with the concept lesson.</small></div><div class="master ${d?'done':''}"><span>${d?'✓ Concept mastered':'Complete the lesson and practice this concept.'}</span><button onclick="master()">${d?'✓ Mastered':'Mark Concept Mastered'}</button></div><div class="actions"><button onclick="prev()" ${topic===0?'disabled':''}>← Previous</button><a class="practice" href="question-bank.html?class=12&chapter=${encodeURIComponent(c.title)}&topic=${encodeURIComponent(t)}">Practice this concept →</a><button class="next" onclick="next()">${topic<c.topics.length-1?'Next concept →':'Chapter complete — choose another chapter'}</button></div></div>`}
function explain(t){const m={'Electric charge':'Electric charge is a fundamental property of matter responsible for electric interactions.','Coulomb’s law':'Coulomb’s law gives the electrostatic force between two point charges and shows that force varies inversely with the square of distance.','Ohm’s law':'Ohm’s law relates potential difference, current and resistance for an ohmic conductor under constant physical conditions.','Electric current':'Electric current is the rate of flow of electric charge through a cross-section.','Photoelectric effect':'The photoelectric effect is the emission of electrons from a material when suitable electromagnetic radiation falls on it.','Semiconductor diode':'A semiconductor diode is a p-n junction device that allows current preferentially in one direction.'};return m[t]||`This concept covers the fundamental principles, definitions, equations and applications of ${t}. Study the concept carefully, work through examples, and then practice related questions.`}
function example(t){return `Focus on the definition, governing principle, important equation where applicable, units, graphs and common applications of ${t}.`}
function openChapter(i){chapter=i;topic=0;render();window.scrollTo({top:0,behavior:'smooth'})}function master(){const d=done();d[chapter+'-'+topic]=true;localStorage.setItem(key,JSON.stringify(d));render()}function next(){if(topic<CLASS12_CONTENT[chapter].topics.length-1){topic++;render();window.scrollTo({top:220,behavior:'smooth'})}}function prev(){if(topic>0){topic--;render()}}render();