const CLASS6_CONTENT = [
{title:'Motion and Measurement of Distances',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ruler.svg',imageAlt:'Metric ruler',imageCredit:'Wikimedia Commons',topics:[['Need for measurement','Measurement gives a numerical value by comparing a quantity with a standard.','A desk can be measured as 120 cm long.'],['Standard units','Standard units allow measurements to be compared. The SI unit of length is metre (m).','1 m = 100 cm and 1 cm = 10 mm.'],['Length measurement','Length is the distance between two points. A ruler or tape can measure suitable objects.','Place the zero mark at one end and read the other end.'],['Correct use of ruler','Keep the ruler along the object and read the scale with your eye directly above the mark.','If the zero edge is damaged, use another starting mark and subtract.'],['Types of motion','Motion is change in position with time. Paths may be straight, circular or repeating.','A car moving on a straight road changes position with time.'],['Rectilinear, circular and periodic motion','Rectilinear motion is along a straight path, circular motion follows a circle, and periodic motion repeats at equal intervals.','A fan blade shows circular motion; a pendulum can show periodic motion.']]},
{title:'Light, Shadows and Reflections',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Light_ill15.gif',imageAlt:'Shadow formation diagram',imageCredit:'Wikimedia Commons',topics:[['Luminous and non-luminous objects','Luminous objects produce their own light. Non-luminous objects are seen when reflected or scattered light reaches our eyes.','The Sun is luminous; the Moon is non-luminous.'],['Transparent, translucent and opaque materials','Transparent materials transmit most light, translucent materials transmit some, and opaque materials block light.','Clear glass, frosted glass and cardboard are examples.'],['Formation of shadows','A shadow forms when an opaque object blocks light from reaching a screen.','Light source → object → screen.'],['Pinhole camera','Light through a tiny hole can form an inverted image on a screen.','A simple box pinhole camera demonstrates straight-line travel of light.'],['Reflection of light','Reflection is the bouncing back of light from a surface.','A plane mirror reflects light.'],['Mirrors and images','A plane mirror forms a virtual, upright image of the same size and shows lateral inversion.','Mirror writing can appear left-right reversed.']]},
{title:'Electricity and Circuits',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Simple-electric-circuit.svg',imageAlt:'Simple electric circuit',imageCredit:'Wikimedia Commons',topics:[['Electric cell','An electric cell is a source of electrical energy with positive and negative terminals.','A dry cell can power a small torch bulb.'],['Terminals of a cell','A cell has positive (+) and negative (−) terminals used to connect a circuit.','Both terminals are needed in a complete circuit.'],['Electric circuit','A circuit is a complete conducting path through which current can flow.','Cell → wire → bulb → wire → cell.'],['Conductors and insulators','Conductors allow current to pass; insulators resist current flow.','Copper is a conductor; plastic is an insulator.'],['Switches','A switch opens or closes the conducting path.','A torch switch completes or breaks its circuit.'],['Simple circuits','A simple circuit needs a source, conducting path and device.','A cell, wires, switch and bulb demonstrate a closed circuit.']]},
{title:'Fun with Magnets',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bar_magnet_on_compass_board_with_field_lines.png',imageAlt:'Bar magnet and field lines',imageCredit:'Wikimedia Commons',topics:[['Magnetic and non-magnetic materials','Magnetic materials are attracted by magnets; common non-magnetic materials are not.','Iron is magnetic; wood is generally non-magnetic.'],['Poles of a magnet','A magnet has north and south poles where its magnetic effect is strongest.','Each piece of a broken magnet has both poles.'],['Attraction and repulsion','Unlike poles attract and like poles repel.','N–S attracts; N–N and S–S repel.'],['Finding directions','A freely suspended magnet tends to align approximately north-south.','This property helps us find directions.'],['Magnetic compass','A compass has a freely rotating magnetic needle that aligns with Earth’s magnetic field.','The marked end points approximately toward geographic north.'],['Making a simple magnet','Suitable iron or steel can be magnetized by repeated stroking in one direction.','A steel needle can be magnetized in a classroom demonstration.']]},
{title:'Temperature and Heat',image:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Thermometer_for_temperature_check.jpg',imageAlt:'Thermometer',imageCredit:'Wikimedia Commons',topics:[['Hot and cold objects','Touch gives a sensation of hot or cold but is not a reliable numerical measurement.','A thermometer gives a numerical reading.'],['Temperature','Temperature indicates how hot or cold an object is and is commonly measured in degrees Celsius at this level.','Body temperature is often around 37 °C, with normal variation.'],['Thermometer','A thermometer is an instrument designed to measure temperature.','Clinical and laboratory thermometers have different purposes.'],['Measuring temperature','Use a suitable thermometer, position it correctly, wait for a steady reading and avoid parallax.','Do not let a liquid thermometer bulb touch the container while measuring a liquid.'],['Heat transfer basics','Heat is energy transferred because of a temperature difference, generally from hotter to colder bodies.','A hot spoon transfers energy to cooler surroundings.'],['Everyday applications','Conduction, convection and radiation explain everyday heating and cooling.','Wool traps air and helps reduce heat loss.']]}
];

let currentChapter=0,currentTopic=0;
const STORE='kp6_mastered';
function totalTopics(){return CLASS6_CONTENT.reduce((n,c)=>n+c.topics.length,0)}
function mastered(){return JSON.parse(localStorage.getItem(STORE)||'{}')}
function renderClass6Content(){const root=document.getElementById('curriculum');if(!root)return;document.title='KP Physics Academy | Class 6 Physics Mastery';root.innerHTML=`<div class="top"><a href="index.html">← Back to Home</a><a href="question-bank.html">Question Bank →</a></div><h1>Class 6 <span>Physics</span></h1><p class="intro">Master one concept at a time. Finish the current concept, then continue to the next concept or freely choose another chapter.</p><div class="progress-wrap"><div><strong>Mastery Progress</strong><span id="progressLabel"></span></div><div class="progress"><div id="progressBar"></div></div></div><h2 class="choose-title">Choose a Chapter</h2><div class="chapter-choices">${CLASS6_CONTENT.map((c,i)=>`<button class="chapter-choice ${i===currentChapter?'active':''}" onclick="openChapter(${i})"><span>${String(i+1).padStart(2,'0')}</span><b>${c.title}</b><small>${c.topics.length} concepts</small></button>`).join('')}</div><div id="lesson"></div>`;renderLesson()}
function renderLesson(){const c=CLASS6_CONTENT[currentChapter],t=c.topics[currentTopic],done=mastered()[currentChapter+'-'+currentTopic];document.getElementById('lesson').innerHTML=`<div class="lesson-card"><div class="lesson-head"><div><span class="chapter-tag">Chapter ${currentChapter+1}: ${c.title}</span><h2>Concept ${currentTopic+1}: ${t[0]}</h2></div><span class="master-status ${done?'done':''}">${done?'✓ Mastered':'Current Concept'}</span></div><div class="lesson-grid"><div><h3>Learn</h3><p>${t[1]}</p><div class="example"><strong>Example:</strong> ${t[2]}</div><div class="key-point"><strong>Key idea:</strong> Master this concept before moving forward.</div></div><figure><img src="${c.image}" alt="${c.imageAlt}" loading="lazy"><figcaption>${c.imageCredit}</figcaption></figure></div><div class="lesson-actions"><a class="practice" href="question-bank.html?class=6&chapter=${encodeURIComponent(c.title)}&topic=${encodeURIComponent(t[0])}">Practice this concept →</a><button onclick="markMastered()">${done?'✓ Concept Mastered':'Mark Concept Mastered'}</button></div><div class="navigation"><button onclick="previousConcept()" ${currentTopic===0?'disabled':''}>← Previous</button><button class="next" onclick="nextConcept()">${currentTopic<c.topics.length-1?'Next concept →':'Chapter complete — choose another chapter →'}</button></div></div>`;updateProgress()}
function openChapter(i){currentChapter=i;currentTopic=0;renderClass6Content();document.getElementById('lesson').scrollIntoView({behavior:'smooth'})}
function markMastered(){const d=mastered();d[currentChapter+'-'+currentTopic]=true;localStorage.setItem(STORE,JSON.stringify(d));renderLesson()}
function nextConcept(){if(currentTopic<CLASS6_CONTENT[currentChapter].topics.length-1){currentTopic++;renderLesson();window.scrollTo({top:300,behavior:'smooth'})}else document.querySelector('.choose-title').scrollIntoView({behavior:'smooth'})}
function previousConcept(){if(currentTopic>0){currentTopic--;renderLesson()}}
function updateProgress(){const n=Object.keys(mastered()).length;document.getElementById('progressLabel').textContent=` ${n} of ${totalTopics()} concepts mastered`;document.getElementById('progressBar').style.width=(n/totalTopics()*100)+'%'}
renderClass6Content();
